---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-7.7
  - name: debian-6.0.10
  - name: centos-6.5
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-test-helpers::consul-template]
    attributes:
      apt:
	compile_time_update: true
      consul_template:
        config:
          consul: '127.0.0.1:8500'
  - name: source
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-test-helpers::consul-template]
    attributes:
      apt:
	compile_time_update: true
      consul_template:
        install_method: 'source'
        config:
          consul: '127.0.0.1:8500'
  - name: runit
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-test-helpers::consul-template]
    attributes:
      apt:
	compile_time_update: true
      consul_template:
        init_style: 'runit'
        config:
          consul: '127.0.0.1:8500'
