Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

AllCops:
  Exclude:
    - 'metadata.rb'
    - '.kitchen*'
    - 'attributes/*'
inherit_from: .rubocop_todo.yml
