language: ruby
sudo: false
bundler_args: --jobs 4 --without integration
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
script:
  - bundle exec rake
notifications:
  email:
    recipients:
      - krone.adam@gmail.com
